name: maven
on:
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        n: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn -B clean install -DskipTests
      - run: cd okapi-common; mvn -B surefire:test -Dtest=PauseResumeTest#test4
